/**
 * generate-pilot.ts — writes the PR3 pilot city pages through the content engine
 * (hub model). Overwrites ONLY the 8 explicitly listed pilot files; never touches
 * preserved-enhancement pages. Branch-only, reversible (git checkout).
 *
 * Run: npx tsx scripts/quality/generate-pilot.ts
 */
import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildCityProfile } from '../../src/lib/content-engine/profile';
import { composeCityContentHub } from '../../src/lib/content-engine/compose';

// 6 REWRITE pilots — all currently templated/clone/thin (safe to improve).
// NOT here (preserved as controls, never overwritten): houston & dallas (4,000-word
// enhanced metros), denver & memphis (preserved enhancements). Overwriting good
// content with thin hubs would violate "preserve good existing content."
const PILOTS: [string, string, string][] = [
  ['california', 'fresno', 'mid-size, Pacific — currently templated (2124w)'],
  ['arizona', 'mesa', 'mid-size top-20, Southwest — currently templated (2037w)'],
  ['arkansas', 'bryant', 'small/FARS-extra, clone offender (2145w)'],
  ['arkansas', 'benton', 'small, adjacent twin of Bryant (2145w clone)'],
  ['connecticut', 'haddam', 'small, Northeast, cross-state clone offender (2166w)'],
  ['vermont', 'burlington', 'small-state, currently thin (835w)'],
];

const LAST_UPDATED = '2026-06-24';

function constName(slug: string): string {
  return slug.toUpperCase().replace(/[^A-Z0-9]/g, '_') + '_CONTENT';
}

function serialize(stateSlug: string, citySlug: string): string | null {
  const p = buildCityProfile(stateSlug, citySlug);
  if (!p) return null;
  const content = composeCityContentHub(p, LAST_UPDATED);
  const cn = constName(citySlug);
  const header = `import type { CityContent } from '../types';

/**
 * ${content.name}, ${content.stateName} — Truck Accident Information (local hub)
 *
 * Generated by content-engine (PR3 pilot, hub model). Renders hero, FARS stats,
 * regional accident mix, trucking-industry note, and local FAQs. Federal substance
 * (evidence/FMCSA/liability) lives on /accidents/[slug], not here.
 * Provenance: roads/SOL/hospitals/courts = NEEDS_SOURCE (never asserted).
 * FARS ${content.accidentStats.dataYear}: ${content.accidentStats.truckFatalities} deaths / ${content.accidentStats.fatalCrashes} crashes.
 */

export const ${cn}: CityContent = ${JSON.stringify(content, null, 2)};

export default ${cn};
`;
  return header;
}

function main() {
  const written: string[] = [];
  const missing: string[] = [];
  for (const [state, city] of PILOTS) {
    const out = serialize(state, city);
    const path = join('src', 'lib', 'cities-content', state, `${city}.ts`);
    if (!out) { missing.push(`${state}/${city}`); continue; }
    if (!existsSync(path)) {
      // Pilot targets must already be routes; do not silently create new ones.
      missing.push(`${state}/${city} (no existing file — skipped)`);
      continue;
    }
    writeFileSync(path, out);
    written.push(`${state}/${city}`);
  }
  console.log('=== PILOT GENERATION (hub model) ===');
  console.log('written:', written.length);
  written.forEach((w) => console.log('  ✓', w));
  if (missing.length) { console.log('missing/skipped:'); missing.forEach((m) => console.log('  ✗', m)); }
}
main();
