/**
 * write-batch.ts — writes the GATED hub batch chosen by batch-preview.ts (--emit).
 * Overwrites ONLY existing city files for the emitted, conflict-free targets. Never
 * creates new routes; never touches the protected sets (pilots / controls / preserved).
 * Branch-only, reversible (git checkout). Run AFTER batch-preview reports PREVIEW PASS.
 *
 * Usage: npx tsx scripts/quality/write-batch.ts [--list=scripts/data/pr5-batch-targets.json] [--limit=50]
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildCityProfile } from '../../src/lib/content-engine/profile';
import { composeCityContentHub } from '../../src/lib/content-engine/compose';

const LAST_UPDATED = '2026-06-24';

// Hard guard — these are NEVER overwritten even if a list names them.
const PROTECTED = new Set([
  'california/fresno', 'arizona/mesa', 'arkansas/bryant', 'arkansas/benton',
  'connecticut/haddam', 'vermont/burlington',
  'texas/houston', 'texas/dallas', 'colorado/denver', 'tennessee/memphis',
  'arizona/tucson', 'california/san-francisco', 'indiana/indianapolis',
  'kentucky/louisville', 'massachusetts/boston', 'michigan/detroit', 'nevada/las-vegas',
  'new-mexico/albuquerque', 'new-york/brookhaven', 'new-york/buffalo', 'new-york/islip',
  'new-york/oyster-bay', 'north-carolina/charlotte', 'oregon/portland',
  'tennessee/nashville', 'texas/el-paso', 'washington/seattle',
]);

function constName(slug: string): string {
  return slug.toUpperCase().replace(/[^A-Z0-9]/g, '_') + '_CONTENT';
}
function serialize(stateSlug: string, citySlug: string): string | null {
  const p = buildCityProfile(stateSlug, citySlug);
  if (!p) return null;
  const content = composeCityContentHub(p, LAST_UPDATED);
  const cn = constName(citySlug);
  return `import type { CityContent } from '../types';

/**
 * ${content.name}, ${content.stateName} — Truck Accident Information (local hub)
 *
 * Generated by content-engine (PR5 gated batch, hub model). Renders hero, FARS stats,
 * regional accident mix, trucking-industry note, and local FAQs. Federal substance
 * (evidence/FMCSA/liability) lives on /accidents/[slug], not here.
 * Provenance: roads/SOL/hospitals/courts = NEEDS_SOURCE (never asserted).
 * FARS ${content.accidentStats.dataYear}: ${content.accidentStats.truckFatalities} deaths / ${content.accidentStats.fatalCrashes} crashes.
 */

export const ${cn}: CityContent = ${JSON.stringify(content, null, 2)};

export default ${cn};
`;
}

function main() {
  const listArg = process.argv.find((x) => x.startsWith('--list='))?.split('=')[1] ?? 'scripts/data/pr5-batch-targets.json';
  const limitArg = process.argv.find((x) => x.startsWith('--limit='))?.split('=')[1];
  const limit = limitArg ? Number(limitArg) : Infinity;
  const targets: string[] = JSON.parse(readFileSync(listArg, 'utf8'));

  const written: string[] = [];
  const skipped: string[] = [];
  for (const key of targets) {
    if (written.length >= limit) break;
    if (PROTECTED.has(key)) { skipped.push(`${key} (PROTECTED)`); continue; }
    const [state, city] = key.split('/');
    const path = join('src', 'lib', 'cities-content', state, `${city}.ts`);
    if (!existsSync(path)) { skipped.push(`${key} (no existing file)`); continue; } // never create routes
    const out = serialize(state, city);
    if (!out) { skipped.push(`${key} (no profile)`); continue; }
    writeFileSync(path, out);
    written.push(key);
  }
  console.log('=== GATED BATCH WRITE (hub model) ===');
  console.log(`written: ${written.length}`);
  written.forEach((w) => console.log('  ✓', w));
  if (skipped.length) { console.log('skipped:'); skipped.forEach((s) => console.log('  ✗', s)); }
}
main();
