/**
 * City Content Index
 *
 * Exports functions and data for city-specific truck accident pages
 */

import type { CityContent, CityAccidentData, StateCitySummary } from './types';

// Import city accident data (generated by FARS collector)
import cityAccidentDataRaw from '../../../scripts/city-accident-data.json';

interface CityAccidentDataFile {
  generatedAt: string;
  totalCities: number;
  totalFatalities: number;
  dataYear: number;
  sourceUrl: string;
  states: Record<string, {
    stateName: string;
    totalFatalities: number;
    cities: CityAccidentData[];
  }>;
}

const cityAccidentData = cityAccidentDataRaw as CityAccidentDataFile;

// State name lookup
const STATE_NAMES: Record<string, string> = {
  alabama: 'Alabama', alaska: 'Alaska', arizona: 'Arizona', arkansas: 'Arkansas',
  california: 'California', colorado: 'Colorado', connecticut: 'Connecticut',
  delaware: 'Delaware', florida: 'Florida', georgia: 'Georgia', hawaii: 'Hawaii',
  idaho: 'Idaho', illinois: 'Illinois', indiana: 'Indiana', iowa: 'Iowa',
  kansas: 'Kansas', kentucky: 'Kentucky', louisiana: 'Louisiana', maine: 'Maine',
  maryland: 'Maryland', massachusetts: 'Massachusetts', michigan: 'Michigan',
  minnesota: 'Minnesota', mississippi: 'Mississippi', missouri: 'Missouri',
  montana: 'Montana', nebraska: 'Nebraska', nevada: 'Nevada',
  'new-hampshire': 'New Hampshire', 'new-jersey': 'New Jersey',
  'new-mexico': 'New Mexico', 'new-york': 'New York',
  'north-carolina': 'North Carolina', 'north-dakota': 'North Dakota',
  ohio: 'Ohio', oklahoma: 'Oklahoma', oregon: 'Oregon', pennsylvania: 'Pennsylvania',
  'rhode-island': 'Rhode Island', 'south-carolina': 'South Carolina',
  'south-dakota': 'South Dakota', tennessee: 'Tennessee', texas: 'Texas',
  utah: 'Utah', vermont: 'Vermont', virginia: 'Virginia', washington: 'Washington',
  'west-virginia': 'West Virginia', wisconsin: 'Wisconsin', wyoming: 'Wyoming',
};

/**
 * Get all cities for a state
 */
export function getCitiesForState(stateSlug: string): CityAccidentData[] {
  const stateData = cityAccidentData.states[stateSlug];
  if (!stateData) return [];
  return stateData.cities;
}

/**
 * Get city accident data by state and city slug
 */
export function getCityData(stateSlug: string, citySlug: string): CityAccidentData | null {
  const cities = getCitiesForState(stateSlug);
  return cities.find(c => c.slug === citySlug) || null;
}

/**
 * Get all city slugs for a state (for generateStaticParams)
 */
export function getCitySlugsForState(stateSlug: string): string[] {
  return getCitiesForState(stateSlug).map(c => c.slug);
}

/**
 * Check if a city exists for a state
 */
export function isValidCity(stateSlug: string, citySlug: string): boolean {
  return getCityData(stateSlug, citySlug) !== null;
}

/**
 * Get all states that have city data
 */
export function getStatesWithCities(): string[] {
  return Object.keys(cityAccidentData.states);
}

/**
 * Get state name from slug
 */
export function getStateName(stateSlug: string): string {
  return STATE_NAMES[stateSlug] || stateSlug;
}

/**
 * Get city summary for all states
 */
export function getAllStateSummaries(): StateCitySummary[] {
  return Object.entries(cityAccidentData.states).map(([stateSlug, state]) => ({
    stateSlug,
    stateName: state.stateName,
    cityCount: state.cities.length,
    totalFatalities: state.totalFatalities,
    cities: state.cities.map(c => c.name),
  }));
}

/**
 * Generate static params for all cities (for generateStaticParams in page.tsx)
 */
export function getAllCityParams(): Array<{ slug: string; city: string }> {
  const params: Array<{ slug: string; city: string }> = [];

  for (const [stateSlug, state] of Object.entries(cityAccidentData.states)) {
    for (const city of state.cities) {
      params.push({
        slug: stateSlug,
        city: city.slug,
      });
    }
  }

  return params;
}

/**
 * Get total city count
 */
export function getTotalCityCount(): number {
  return cityAccidentData.totalCities;
}

// Re-export types
export type { CityContent, CityAccidentData, StateCitySummary } from './types';
