/**
 * Prebuild step: scan public/brand/photo for available pro image assets and
 * write a static manifest the app imports (works in both server + client).
 * Drop a correctly-named .webp/.avif/.jpg/.png into public/brand/photo and the
 * next build will wire it automatically by slug — no code change needed.
 */
import { readdirSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

const photoDir = join(process.cwd(), 'public', 'brand', 'photo');
if (!existsSync(photoDir)) mkdirSync(photoDir, { recursive: true });

const files = readdirSync(photoDir)
  .filter((f) => /\.(webp|avif|jpe?g|png)$/i.test(f))
  .sort();

const out = `// AUTO-GENERATED by scripts/gen-image-manifest.ts (npm prebuild). Do not edit by hand.
export const AVAILABLE_PHOTOS: string[] = ${JSON.stringify(files, null, 2)};
`;

writeFileSync(join(process.cwd(), 'src', 'lib', 'brand-images.generated.ts'), out);
console.log(`[gen-image-manifest] ${files.length} photo asset(s) found in public/brand/photo`);
